name: Deploy to Azure App Service via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name kishorenestleacr

      - name: Build and Push Docker image
        run: |
          docker build --platform=linux/amd64 \
            -t kishorenestleacr.azurecr.io/nestle-chatbot:latest .
          docker push kishorenestleacr.azurecr.io/nestle-chatbot:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name nestle-assistant \
            --resource-group kishore-project-nestle \
            --container-image-name kishorenestleacr.azurecr.io/nestle-chatbot:latest \
            --container-registry-url https://kishorenestleacr.azurecr.io \
            --container-registry-user $(az acr credential show --name kishorenestleacr --query username -o tsv) \
            --container-registry-password $(az acr credential show --name kishorenestleacr --query passwords[0].value -o tsv)

      - name: Restart Web App
        run: az webapp restart --name nestle-assistant --resource-group kishore-project-nestle
